name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  pull_request:

jobs:
  analyze:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter: [ '2.8.0' ]
        include:
          - os: ubuntu-latest
            build: apk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  build:
    needs: analyze
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        flutter: [ '2.8.0' ]
        include:
          - os: ubuntu-latest
            target: android
            build: apk --split-per-abi
            path: 'build/app/outputs/apk/release/'
          - os: macos-latest
            target: iOS
            build: 'ios --no-codesign'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        if: ${{ matrix.target == 'android' }}
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}
          cache: true
      - run: flutter build ${{ matrix.build }}
      - uses: actions/upload-artifact@v1
        if: ${{ matrix.target == 'android' }}
        with:
          name: release-${{ matrix.build }}
          path: ${{ matrix.path }}
  web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          cache: true
      - name: Build
        run: flutter build web --base-href "${GITHUB_REPOSITORY#"$GITHUB_REPOSITORY_OWNER"}"'${{ github.base_ref }}/'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: ${{ github.base_ref }}
