name: push
on:
  push:

jobs:
  web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          cache: true
      - name: Build
        run: |
          flutter build web --base-href "${GITHUB_REPOSITORY#"$GITHUB_REPOSITORY_OWNER"}"'/${{ github.ref }}/'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: ${{ github.ref }}
